import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const SITE_URL = (process.env.SITE_URL ?? "https://biki-portfolio.vercel.app").replace(/\/$/, "");

// ─── Default site-wide SEO ───
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Biki Kalita — ML Engineer",
    template: "%s · Biki Kalita",
  },
  description:
    "ML engineer based in Assam, India. I build and deploy machine learning systems — XGBoost, scikit-learn, FastAPI, Docker. Open to work.",
  keywords: [
    // Primary role keywords
    "ML Engineer",
    "Machine Learning Engineer",
    "Software Engineer",
    "Data Scientist",
    // Skill keywords
    "Machine Learning",
    "Data Science",
    "Predictive Modeling",
    "Regression",
    "Classification",
    "XGBoost",
    "Scikit-learn",
    "Feature Engineering",
    "EDA",
    "Exploratory Data Analysis",
    // Stack keywords
    "Python",
    "FastAPI",
    "Flask",
    "REST APIs",
    "Backend",
    "Docker",
    "Pandas",
    "NumPy",
    // Domain keywords
    "ML workflows",
    "Inference APIs",
    "Model Deployment",
    "Data Readiness",
    // Location / name
    "Biki Kalita",
    "ML Engineer portfolio",
  ],
  authors: [{ name: "Biki Kalita", url: SITE_URL }],
  creator: "Biki Kalita",
  publisher: "Biki Kalita",
  applicationName: "Biki Kalita — Portfolio",
  category: "Technology",
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "profile",
    locale: "en_US",
    url: SITE_URL,
    siteName: "Biki Kalita — ML Engineer",
    title: "Biki Kalita — ML Engineer",
    description:
      "ML engineer based in Assam, India. I build and deploy machine learning systems — XGBoost, scikit-learn, FastAPI, Docker. Open to work.",
    firstName: "Biki",
    lastName: "Kalita",
    username: "Biki989",
    images: [
      {
        url: "/icon.svg",
        width: 512,
        height: 512,
        alt: "Biki Kalita — ML Engineer",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Biki Kalita — ML Engineer",
    description:
      "ML engineer based in Assam, India. I build and deploy machine learning systems.",
    images: ["/icon.svg"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  manifest: "/manifest.json",
};

export const viewport: Viewport = {
  themeColor: "#F2F3F5",
  width: "device-width",
  initialScale: 1,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the per-request nonce generated by middleware. This does two things:
  //  1. Returns the nonce so we can pass it to our own inline <script> tags.
  //  2. Signals to Next.js that it should auto-apply the nonce to its own
  //     inline scripts (hydration data, runtime config, etc.).
  const nonce = (await headers()).get("x-nonce") ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster nonce={nonce} />
      </body>
    </html>
  );
}
